# Generated by Django 5.2.6 on 2025-09-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_user_unique_lower_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
