# Generated by Django 5.2.6 on 2025-09-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='share_id',
            field=models.UUIDField(blank=True, help_text='Unique identifier for public sharing of this event.', null=True, unique=True),
        ),
    ]
