# Generated by Django 5.2.6 on 2025-09-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_created_at_alter_event_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, help_text='Where the event takes place (optional)', null=True),
        ),
    ]
