# Generated by Django 5.2.6 on 2025-09-19 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(default=1, help_text='Where the event takes place', validators=[django.core.validators.MinLengthValidator(5)]),
            preserve_default=False,
        ),
    ]
